### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by mjkim610** [mjkim610/sherlock#7]
sha256.js - https://code.google.com/archive/p/crypto-js/ uses the 3-Clause BSD license.
sherlock license must be updated.

**Comment by sullamij** [comment]
원본 라이선스가 종종"BSD-old" 로 참고되어지고 있는만큼, 여기서 파생된3-조항 버전은"BSD-new" 로 불리기도 한다. 다른 이름으로는"New BSD", "revised BSD", "BSD-3" 혹은"3-조항BSD" 이 있다.
참고로 "New BSD"라는 말을 쓰고는 있지만, BSD 라이선스의 가장 최신 버전은 아니다. 이 버전 이후 "Simplified BSD 라이선스"라고 알려진 BSD-2-Clause 버전이 나왔다. 2008년1월9일, OSI 이사회는 FreeBSD 등에 사용되며, 마지막의 "홍보 불가(no-endorsement)" 조항을 삭제하여 결과적으로MIT 라이선스와 거의 동등해진 "Simplified BSD 라이선스"를 승인했다.

The BSD 3-clause and the MIT license are both "GPL-compatible" and can be redistributed in GPL-licensed projects. But the difference selecting between BSD 3-clause and the MIT one, would be- that if we really want the "no endorsement" clause to apply then, we have to license it as just BSD (not dual). But If we don't care about the "no endorsement" clause, then MIT alone is sufficient and MIT/BSD is redundant.

What do you think about the "endorsement" issue? 
I would soon revise the license to the most adoptable license to our project.

**Comment by mjkim610** [comment]
According to https://softwareengineering.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license
BSD-3 cannot be used/redistributed through MIT.
Unless we have good reasons for sticking to MIT, I suggest we switch to a license that complies with code that we use.
